import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { seongsuPlaces } from "../data/places";
import type { OpeningHour, Place, PlaceSource } from "../types/place";

export interface DatabasePlaceRow {
  id: string;
  name: string;
  category: Place["category"];
  latitude: number;
  longitude: number;
  address: string;
  avg_price: number;
  avg_stay_duration_min: number;
  tags: string[];
  indoor: boolean;
  opening_hours: OpeningHour[];
  data_status: Place["dataStatus"];
  sources: PlaceSource[];
  price_source_type: Place["priceSourceType"];
  opening_hours_source_type: Place["openingHoursSourceType"];
  last_verified_at: string;
  valid_from: string | null;
  valid_until: string | null;
  score_source: Place["scoreSource"];
  scores: Place["scores"];
}

const columns: ReadonlyArray<keyof DatabasePlaceRow> = [
  "id",
  "name",
  "category",
  "latitude",
  "longitude",
  "address",
  "avg_price",
  "avg_stay_duration_min",
  "tags",
  "indoor",
  "opening_hours",
  "data_status",
  "sources",
  "price_source_type",
  "opening_hours_source_type",
  "last_verified_at",
  "valid_from",
  "valid_until",
  "score_source",
  "scores",
];

export function placeToDatabaseRow(place: Place): DatabasePlaceRow {
  return {
    id: place.id,
    name: place.name,
    category: place.category,
    latitude: place.lat,
    longitude: place.lng,
    address: place.address,
    avg_price: place.avg_price,
    avg_stay_duration_min: place.avg_stay_duration_min,
    tags: place.tags,
    indoor: place.indoor,
    opening_hours: place.opening_hours,
    data_status: place.dataStatus,
    sources: place.sources,
    price_source_type: place.priceSourceType,
    opening_hours_source_type: place.openingHoursSourceType,
    last_verified_at: place.lastVerifiedAt,
    valid_from: place.validFrom ?? null,
    valid_until: place.validUntil ?? null,
    score_source: place.scoreSource,
    scores: place.scores,
  };
}

function escapeSqlText(value: string): string {
  if (value.includes("\0")) {
    throw new Error("SQL text values cannot contain null bytes.");
  }
  return `'${value.replaceAll("'", "''")}'`;
}

function sqlJson(value: OpeningHour[] | PlaceSource[] | Place["scores"]): string {
  return `${escapeSqlText(JSON.stringify(value))}::jsonb`;
}

function sqlTextArray(values: string[]): string {
  return values.length === 0 ? "ARRAY[]::text[]" : `ARRAY[${values.map(escapeSqlText).join(", ")}]::text[]`;
}

function rowValues(row: DatabasePlaceRow): string {
  const values = [
    escapeSqlText(row.id),
    escapeSqlText(row.name),
    escapeSqlText(row.category),
    String(row.latitude),
    String(row.longitude),
    escapeSqlText(row.address),
    String(row.avg_price),
    String(row.avg_stay_duration_min),
    sqlTextArray(row.tags),
    row.indoor ? "true" : "false",
    sqlJson(row.opening_hours),
    escapeSqlText(row.data_status),
    sqlJson(row.sources),
    escapeSqlText(row.price_source_type),
    escapeSqlText(row.opening_hours_source_type),
    escapeSqlText(row.last_verified_at),
    row.valid_from ? escapeSqlText(row.valid_from) : "null",
    row.valid_until ? escapeSqlText(row.valid_until) : "null",
    escapeSqlText(row.score_source),
    sqlJson(row.scores),
  ];
  return `  (${values.join(", ")})`;
}

export function generatePlaceSeedSql(places: readonly Place[]): string {
  const ids = new Set(places.map((place) => place.id));
  if (ids.size !== places.length) {
    throw new Error("Cannot generate place seed: place IDs must be unique.");
  }

  const rows = [...places]
    .sort((left, right) => (left.id < right.id ? -1 : left.id > right.id ? 1 : 0))
    .map(placeToDatabaseRow);
  const updateColumns = columns.filter((column) => column !== "id");

  return [
    "-- Generated by scripts/generate-place-seed.ts. Do not edit manually.",
    "insert into public.places (",
    `  ${columns.join(",\n  ")}`,
    ") values",
    `${rows.map(rowValues).join(",\n")}`,
    "on conflict (id) do update set",
    `${updateColumns.map((column) => `  ${column} = excluded.${column}`).join(",\n")};`,
    "",
  ].join("\n");
}

export async function writePlaceSeedFile(outputPath = resolve(process.cwd(), "supabase/seed.sql")): Promise<void> {
  const sql = generatePlaceSeedSql(seongsuPlaces);
  await writeFile(outputPath, sql, "utf8");
}

if (require.main === module) {
  void writePlaceSeedFile().then(() => {
    console.log(`Generated supabase/seed.sql with ${seongsuPlaces.length} places.`);
  });
}
